### ISSUE TITLE
Return biosimulators metadata

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1401]
- [x] I think `schemaVersion` could be unclear. Rename to `specificationsVersion`. -- done in #1421.
- [x] We need to have the ability to return the biosimulators metadata. I think this may also be fixed by #1421.
  - `schemaVersion`
  - `imageVersion`
- [x] This part of the schema should appear in the documentation at api.biosimulators.org. I think this may also be fixed by #1421.

**Comment by bilalshaikh42** [comment]
The biosiumulators metadata should return. The current database simply does not contain entries with the metdata defined. Once the entries are updated, the value will return

**Comment by bilalshaikh42** [comment]
For example, this call returns the data https://api.biosimulators.org/simulators/latest?id=gillespy2

**Comment by jonrkarr** [comment]
Looks good, except I'd like to rename `schemaVersion` to `specificationsVersion` to be clearer about the meaning of this field. I changed this in #1421.
