### ISSUE TITLE
Connect local storage of simulations in runBioSimulations to API and debug

### ISSUE THREAD

**Issue by gmarupilla** [reproducible-biomedical-modeling/CRBM-Viz#1496]
**Please describe the bug**
If we share the URL to visualization, it won't work on other browsers. Would only work on the browser where the simulations are stored in the browser's local DB.

**Please describe how to reproduce the bug**
1. Dispatch a simulation from runbiosimulations
2. When it finishes, copy the URL
3. Paste and go to the URL in the incognito tab/window
4. There would be no data/visualization visible.

**How should BioSimulations have behaved**
The Simulation info, design, and visualization should be functional even if it's incognito or opened by another user on other computers.

Currently, all the simulation info is loaded (using Simulation Service) in the app only when the "Your Simulations" page is initialized. When we go to the logs/visualization page, it just uses the information from local storage to render as simulation info.

If we directly open the sim info URL ('view' component), the 'browse' component is never initialized, and therefore local storage is never initialized.

IMO, we should stop using local storage on the 'view' component, and fetch the sim info again (from dispatch API) on the 'view' component initialize for the respective simulation (using UUID).

@bilalshaikh42   @jonrkarr  thoughts?

URL: https://run.biosimulations.org/simulations/662d7e68-4efb-48aa-82aa-aa9a7b73886f

**Comment by jonrkarr** [comment]
The implementation of this is not yet complete. I implemented most of this, but couldn't complete it because the API is still only partly functional. 

The intended behavior is below.

When the app is opened, the following should happen:
1. The list of simulations that the user has worked with is loaded from local storage
2. The status of each of these is fetched from the API

Each time the user opens a page of a simulation
- It should be fetched from the API
- It should be added to local storage if its not already in local storage

**Comment by jonrkarr** [comment]
@gmarupilla I looked into this. `apps/dispatch/src/app/services/simulation/simulation.service.ts.getSimulationByUuid` is not implemented as intended. `getSimulationByUuid` should query the API not local storage. Querying of a simulation that isn't stored in local storage should result in adding the simulation to the local storage.

I'm working on sorting this out. Unfortunately, its hard to make sure everything is working because the dispatch API isn't working right now. I'll have to finish debugging this when the API is available.

**Comment by jonrkarr** [comment]
I brought this issue up in September as #1170. I had assigned this to @gmarupilla to connect with the API.

**Comment by jonrkarr** [comment]
Remaining todo:
- [ ] Check that app periodically polls API for updated status of simulations
- [ ] Check that simulation export button works
- [ ] Check that simulation import button works
- [ ] Check that simulations not stored in local storage can be opened, and this results in adding an additional simulation to local storage

**Comment by jonrkarr** [comment]
@gmarupilla @bilalshaikh42 please let me know when the API is working so I can finish making sure the local storage and retrieval from the database is working as intended.

**Comment by bilalshaikh42** [comment]
#1630 fixed the job submissions. This is working 
#1629 Should have addressed the results. I am not sure about this one. @gmarupilla  can confirm.

**Comment by bilalshaikh42** [comment]
There was a bug in the submission of the jobs. The API is working for the following steps: 
1) Using the /run path, create a simulations run. This creates a run with the status of Queued
2) Use the /jobinfo path to get the structure of the results
3) Use the /result path with the information from the step 2 to view the results

Issues to address: 
1) The status of the Job is not being updated. 
2) The steps to get the results need to be changed to just call the /results enpoint

I think changing the front end to use the the simpler path is doable by next week. We can discuss tomorrow if we want to keep the current api and connect the front end or use the /results enpoint. 

In either case, we can have the job updating properly shortly. All that needs to be done is to make a patch request from the service to the API. #1640

**Comment by jonrkarr** [comment]
## Status
I don't think it's critical to display detailed status to users now. For now, the status displayed to users could just be "Not yet run", "Succeeded", and "Failed", where 
- "Not yet run" covers created, queued, started, and running and 
- "Failed" covers all errors including run time errors, out of memory, time out, etc. 

Does that simplify things?

## Todos
I don't quite follow what needs to be done with respect to the API, service, and frontend. I can take care of any frontend stuff. I just need to know which endpoints to query for different information. We can sort this out tomorrow.

**Comment by bilalshaikh42** [comment]
There is no real difference between the level of detail. The status just needs to be sent to the API either way.  @gmarupilla has already implemented monitoring the status. But right now, only the service is aware of the information

The breakdown between the  components is as follows: The API handles the database entries for the simulations runs, and has the information about user, filename, email, times etc. It provides methods for the front end to submit jobs, and retrieve results.
 
The service is responsible for connecting to the HPC to start jobs, monitoring the jobs, and getting the results from the HPC. It then uses the  API to then save the results and update the information.  This last step is what remains to be implemented

**Comment by jonrkarr** [comment]
Thanks. I think I now understand what need to be done.

**Comment by gmarupilla** [comment]
The required APIs are now working, changes will be merged with PR #1637. 
Note: I've not tested/fixed all APIs. The APIs required for running a simulation, get logs, download results, get results in json format, get json data for chart, get result structure. All these are working. I've also plugged them with frontend. 

Simulations are running end to end via frontend. Status are being updated as required as well (fixes #1640 )

@jonrkarr @bilalshaikh42 please review.

**Comment by jonrkarr** [comment]
I substantially revised the view component and simulation service.

I believe this is working now. 
- Simulations are no longer dropped from the history -- this was due to saving to local storage before local storage finished initializing
- Simulations run by other people or on other machines can be opened. This causes the simulation to be appended to local storage and its status updated using the API.

I also:
- Set up the view component to also poll the API for updates when the status is created, queued, or running. This now behaves similarly to the browse simulations component.
- Fixed the enabled/disabled status of tabs and select boxes based on the properties of the simulation and its outputs.
- Fixed the change detection errors partly by passing viz data directly to the visualization component rather than through the visualization service
