### ISSUE TITLE
Add REST endpoint and web form for getting similar algorithms

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2520]
from @bilalshaikh42 
> Is this something that we could put behind and endpoint to enable these
features from biosimulation as well?
Does d. imply that the "isImplementedIn" field of Kisao is now being
updated? Or is this pinging the biosimulators database?

**Comment by jonrkarr** [comment]
## Done/soon to be done: Status of incorporation into BioSimulations
The substitutability of algorithm terms will be included in the next version of each of the simulation tools (except VCell). I think we should hold off pushing these versions to the BioSimulators database until we hear back from reviewers (they will be pushed to GitHub, but not released).

## Todo: Expose the new functionality independently of simulation tools
- [x] Add endpoint to get algorithms similar to a given algorithm
    - Return a list of algorithms
       - KiSAO id
       - Level of compatibility of each algorithm
- [x] Intersect the above with information from the simulators database
   - Return a list of compatible simulation tools
      - Simulator id
      - Level of compatibility of with desired algorithm
      - Algorithms implemented by the tool at that level of compatibility
- [x] Add web form for the above
- [x] Integrate similar functionality into dispatch simulation form
- [x] Integrate similar functionality into build project form

## Discussion: `isImplementedIn` field in KiSAO
What I implemented doesn't use the `isImplementedIn` field in KiSAO. It mainly uses (a) the relationships among algorithm terms, and (b) the properties of algorithm terms. I also included 1 function which is intended to utilize information provided by a simulation tool about its own capabilities (rather than information derived from the `isImplementedIn` field in KiSAO).

A couple months ago I replaced all of the values of `isImplementedIn` with URLs to BioSimulators (e.g., `copasi` --> `https://biosimulators.org/simulators/copasi`).

I think the `isImplementedIn` field is tough to work with:
- Many relationships are missing (i.e., there are false negatives)
- There's no quality control over this information (i.e., there are false positives)
- The open world nature of KiSAO is hard to square with the closed-world nature of the BioSimulators registry. E.g., in KiSOA you can say that (a) CVODE has parameters X, Y, and Z and (b) CVODE is implemented by tellurium and VCell. With KiSAO, this implies that tellurium-CVODE and VCell CVODE both expose arguments for X, Y, and Z. However, this the parameters of tellurium-CVODE and VCell-CVODE are different. KiSAO would need much more information and refactoring to correct this, in which case KiSAO would start to look a lot like BioSimulators.
