### ISSUE TITLE
Update `PYPI_TOKEN` GitHub organization secret

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3882]
The PyPI token (https://github.com/biosimulations/biosimulations/settings/secrets/actions) no longer works. A new token needs to be generated for the `biosimulations` PyPI account and saved to `PYPI_TOKEN`. I can't do this because I don't have access to the PyPI account or its recovery email address. 

## Temporary work around
Temporarily, I've set `PYPI_TOKEN` to a token for the `biosimulators` PyPI account. This enabled me to publish the `biosimulations-bigg` package under the `biosimulators` PyPI account.

## Todo
- [x] Verify email address for the `biosimulations` PyPI account
- [x] Generate token for the `biosimulations` PyPI account
- [x] Save token to `PYPI_TOKEN` secret for this (BioSimulations) GitHub organization
- [x] Transfer ownership of the `biosimulations-bigg` PyPI project from the `biosimulators` PyPI account to the `biosimulations` PyPI account -- I can help with this part
  - [x] Use the `biosimulators` account to add the `biosimulations` account as an owner
  - [x] Use the `biosimulations` account to confirm ownership
  - [x] Remove the `biosimulators` account as an owner

**Comment by bilalshaikh42** [comment]
The pypi account is tied to the biosimulationsdaemon@gmail.com account and has been verified. It was set to info@biosimulations.org previously, but this just forwards to the daemon account anyway. I can send you the login info for the daemon account if needed

**Comment by jonrkarr** [comment]
Thanks.
