### ISSUE TITLE
Change partition, qos, constraint in SBATCH template to use new UConn HPC configuration

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3891]
Follows up on our discussion from 2021-12-23.

@mpw6 The SBATCH templates are defined at the location below. Please put any notes here about what we should change

## Todo
- [x] Add `#SBATCH --constraint="simulations&SSE42"`
- [x] Change `HPC_SLURM_QOS` as `simulations`
- [x] Change `HPC_SLURM_PARTITION` to `global`

## Related files

https://github.com/biosimulations/biosimulations/blob/dev/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts#L152

https://github.com/biosimulations/biosimulations/blob/dev/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts#L240

**Comment by jonrkarr** [comment]
Partitioned cannot currently be changed to `global` because `singularity run` stalls on those nodes. This requires help from @mpw6.

**Comment by jonrkarr** [comment]
On hold because some of the UConn nodes need to be re-provisioned because Singularity isn't working on them. This is expected to take a few weeks. Can be completed once @mpw6 informs us that re-provisioned is completed.

**Comment by jonrkarr** [comment]
Done
