### ISSUE TITLE
Switch to use general Singularity module in UConn HPC rather than custom BioSimulations module

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3892]
Follows up on our discussion from 2021-12-23.

BioSimulations is currently using the `singularity/3.7.1-biosim` module in `/home/FCAM/crbmapi/module/`.

@mpw6 please let us know if we should switch to a different module

## Todo
- [x] Change `HPC_EXECUTABLES_PATH` configuration variable to `"PATH=$PATH"`
- [x] Change `HPC_MODULE_PATH` configuration variable to `/isg/shared/modulefiles`
- [x] Change `HPC_SINGULARITY_MODULE` configuration variable to `singularity/3.9.2`
- [x] Remove manually changing working directory in sbatch script since already set declarative through SBATCH configuration 
- [x] Move dispatch-service-related configuration from shared config to dispatch-service config
- [x] Simplify name of sbatch file to job.sbatch
- [x] Organize Singularity loading in sbatch template 

### Configuration is defined here
https://github.com/biosimulations/deployment/blob/main/config/prod/dispatch-service/config.env#L6
https://github.com/biosimulations/deployment/blob/main/config/prod/shared.env#L21

### SBATCH templates are here
https://github.com/biosimulations/biosimulations/blob/dev/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts#L152
https://github.com/biosimulations/biosimulations/blob/dev/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts#L240

**Comment by bilalshaikh42** [comment]
Switching to singularity/3.9.2 from regular module directory
