### ISSUE TITLE
Add and ensure permissions for service accounts to use multi-part uploads

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4078]
Running the sumbit script casues the following error for the RVA simulation. Disabled this particular one allows remaining simulations to proceed.

```
Traceback (most recent call last):
  File "/home/bilal/Projects/work/Biosimulations/tools/submit-example-simulation-runs", line 383, in <module>
    main(runbiosimulations_deployment=args.runbiosimulations_deployment,
  File "/home/bilal/Projects/work/Biosimulations/tools/submit-example-simulation-runs", line 198, in main
    raise RuntimeError('Simulation could not be run on {}: {}'.format(
RuntimeError: Simulation could not be run on https://api.biosimulations.dev/runs: [{'status': '500', 'title': 'An error occurred in uploading the COMBINE archive for the simulation run: Access denied..', 'meta': {'err': {}, 'time': 1642555208971, 'url': '/runs'}}]
```

Im confused that this seems to be happening when saving the combine archive to the cloud bucket. There might some particular filename causing this. I have no idea how this can cause a permissions issue. This might be an issue with downloading the archive that  the error handling is misattributing to uploading the archive

## Todo
- [x] Adjust bucket settings to allow larger files
- [x] Re-enable RBA example simulation in `tools/example-projects.json`

- [ ]  Enable and test permissions for dev service account 
- [ ] Enable and test permissions for prod service account

**Comment by jonrkarr** [comment]
This archive is larger than the others (12 MB). Is there a file size limit configuration on the bucket?

**Comment by jonrkarr** [comment]
I can replicate this with boto3, other files, other S3 keys, and other buckets.

This must be due to configuration of the bucket. There appears to be a limit at 8388608 bytes = 8 MB.

Maybe this relates to `content-length-range`. See https://cloud.google.com/storage/docs/authentication/signatures#:%7E:text=Content%20Length%20Range

Here's some Python code to easily replicate this.

```python
import boto3
import os
import tempfile

endpoint_url = 'https://storage.googleapis.com'
bucket_name = 'biosim-temp-dev'
aws_access_key_id = '...'
aws_secret_access_key = '...'

s3 = boto3.resource(
    's3',
    endpoint_url=endpoint_url,
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    verify=False,
)
bucket = s3.Bucket(bucket_name)

client = boto3.client('s3',
                      endpoint_url=endpoint_url,
                      aws_access_key_id=aws_access_key_id,
                      aws_secret_access_key=aws_secret_access_key,
                      verify=False,
                      )

key = 'test-large-file.omex'

# upload small file to temporary storage bucket and then delete it
file_size = int(1e6)
fid, filename = tempfile.mkstemp()
os.close(fid)
with open(filename, 'wb') as file:
    file.write(b'1' * file_size)
bucket.upload_file(filename, key)
client.delete_object(
    Bucket=bucket_name,
    Key=key,
)
os.remove(filename)

# upload max allowed size to temporary storage bucket and then delete it
file_size = 8388607
fid, filename = tempfile.mkstemp()
os.close(fid)
with open(filename, 'wb') as file:
    file.write(b'1' * file_size)
bucket.upload_file(filename, key)
client.delete_object(
    Bucket=bucket_name,
    Key=key,
)
os.remove(filename)

# upload large file to temporary storage bucket and then delete it
file_size = 8388608
fid, filename = tempfile.mkstemp()
os.close(fid)
with open(filename, 'wb') as file:
    file.write(b'1' * file_size)
bucket.upload_file(filename, key)
client.delete_object(
    Bucket=bucket_name,
    Key=key,
)
os.remove(filename)
```

**Comment by jonrkarr** [comment]
Was due to multipart uploading not being enabled for the accounts we're using with the buckets.

**Comment by bilalshaikh42** [comment]
@jonrkarr is this confirmed to be working now? I was not sure if the permission got applied correctly

**Comment by jonrkarr** [comment]
It worked for me on dev. Since you applied the same settings to the Google cloud account for prod, prod should work too.

**Comment by bilalshaikh42** [comment]
perfect, thanks!
