### ISSUE TITLE
Support SED-ML L1V4 styles

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4227]
Some SED-ML files from BioModels need line and marker styles

## Todo
- [x] Add models to COMBINE API using ApiCurio
- [x] Add to SED-ML reading by COMBINE API: `apps/combine-api/src/handlers/combine/get_sedml_specs_for_combine_archive.py`
- [x] Add to SED-ML writing by COMBINE API:  `apps/combine-api/src/handlers/combine/utils.py`
- [x] Re-generate COMBINE API angular library
- [x] Re-generate COMBINE API nest library
- [x] Add to SED-ML specifications model used by API
  - [x] `apps/api/src/specifications/specifications.model.ts`
  - [x] `libs/datamodel/common/src/lib/sedml/sedml.ts`
  - [x] `libs/ontology/datamodel/src/lib/specifications/specifications.ts`
  - [x] `libs/simulation-runs/service/src/lib/sed-document/sed-document.ts` 
  - [x] Add validator for hexidecimal colors to `libs/datamodel/utils/src/lib/`
- [x] Use with Plotly: `libs/simulation-runs/service/src/lib/sed-plot-2d-visualization/sed-plot-2d-visualization.service.ts`

### `Style`
Interface
- `line`: `Line`
- `marker`: `Marker`
- `fill`: `Fill`

### `Line`
Interface:
- `type`: `LineType` { use="optional" }
- `color`: `SedColor` { use="optional" }
- `thickness`: double { use="optional" }

### `Marker`
Interface
- `type`: `MarkerType` { use="optional" }
- `size`: double { use=”optional” }
- `fill`: `SedColor` { use="optional" }
- `lineColor`: `SedColor` { use="optional" }
- `lineThickness`: double { use="optional" }

### `Fill`
Interface 
- `color`: `SedColor`

### `LineType`
Enumeration:
- `none`
- `solid`
- `dash`
- `dot`
- `dashDot`
- `dashDotDot`

### `MarkerType`
Enumeration:
- `none`
- `square`
- `circle`
- `diamond`
- `xCross`
- `plus`
- `star`
- `triangleUp`
- `triangleDown`
- `triangleLeft`
- `triangleRight`
- `hDash`
- `vDash`

### `SEDColor`
string with one of the formats:
- Six-character RGB hex value
- Eight-character RGBA hex value
